### ISSUE TITLE
Investigate huge surge in 404 errors for deleted snapshots

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-block-tracker#34]
Currently our data retention policy is to delete snapshots after 24 hours.

Once the snapshot snap-1035148 was deleted we got a huge surge in requests for this snapshot which, obviously, now returns 404 errors.

![Screenshot_20211003-023134_Chrome](https://user-images.githubusercontent.com/3359418/135736410-7e9e0759-3248-4d7f-8ea8-8e5e811ee3e1.jpg)
![Screenshot_20211003-012955_Chrome](https://user-images.githubusercontent.com/3359418/135736412-3afa0c39-39ff-46e8-80c2-6a9d798a3b40.jpg)

We need to investigate the cause of this, and maybe consider increasing the retention policy to 1 week (or perhaps 2 or 4 weeks?) so we retain the snapshots through at least one or two GAs perhaps?

4 weeks of snapshots (about 25GB) will cost ~$1 a month on GCP so not going to break the bank.

**Comment by shawaj** [comment]
Temporarily bumped retention to 28 days whilst we investigate

**Comment by vpetersson** [comment]
@robputt Could you take a look at this?

**Comment by shawaj** [comment]
My guess is that perhaps the snapshots are subsequently requested by other (non-Nebra) hotspots over libp2p or something similar.

Not entirely sure

**Comment by shawaj** [comment]
Since I pushed the latest update to production this is tailing off, so closing for now and will keep an eye on it

![Screenshot_20211006-043918_Chrome](https://user-images.githubusercontent.com/3359418/136137087-521fe21d-93c6-40e2-add1-002b8d4798c4.jpg)
