### ISSUE TITLE
Upstream Config Changes

### ISSUE THREAD

**Issue by robputt** [NebraLtd/hm-block-tracker#35]
https://github.com/helium/miner/commit/9a124fea3599a00c52f355113aca463862933fb4

**Comment by shawaj** [comment]
Have left open as we may need to change latest.json to be latest-snap.json like it is upstream, and change the hash format as per:

https://engineering.helium.com/2021/10/27/blockchain-release-auto-snaps-and-bug-fixes.html

Upstream latest-snap.json
https://snapshots.helium.wtf/mainnet/latest-snap.json

Our latest.json
https://storage.googleapis.com/helium-snapshots.nebra.com/latest.json

**Comment by shawaj** [comment]
@robputt @marvinmarnold @vpetersson we need to urgently test and fix this...as in, today.

**Comment by vpetersson** [comment]
My findings so far:

* `latest.json` is generated by [this line](https://github.com/NebraLtd/hm-block-tracker/blob/master/snapshotter/create_snapshot.sh#L8), which the new format breaks.
* We currently don't differentiate between stage and prod URLs for [docker.config](https://helium-assets.nebra.com/docker.config), which means if we change to the new format, all existing miners will presumably break.

**Comment by vpetersson** [comment]
* I've now created helium-assets-stage.nebra.com and https://helium-snapshots-stage.nebra.com such that we can test these new changes without breaking production. 
* We are currently testing some changes but still haven't been able to construct the new format programmatically.

**Comment by vpetersson** [comment]
* We also need to rename `latest.json` to `latest-snap.json`

**Comment by shawaj** [comment]
> * We also need to rename `latest.json` to `latest-snap.json`

we need both latest.json and latest-snap.json as the hash formatting is different

**Comment by shawaj** [comment]
the new format is base58

**Comment by shawaj** [comment]
Supersede by #42
