### ISSUE TITLE
Auto-generate and deploy `docker.config` as part of the cronjob

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-block-tracker#42]
The miner is automatically [pulling](https://github.com/NebraLtd/hm-miner/blob/master/start-miner.sh#L11) `docker.config` as part of the start process. However, this file is currently served from [helium-assets.nebra.com](https://helium-assets.nebra.com), which in turn isn't automatically generated and deployed.

I suggest that we:
* Update the [GitHub Workflow](https://github.com/NebraLtd/hm-block-tracker/blob/master/.github/workflows/run-update.yml) to use the master branch for 'TestNet' and the production branch for MainNet.
  * This way we can easily test new GA and breaking changes on TestNet without impacting MainNet
* Point all of TestNet to helium-snapshots-stage.nebra.com using the Fleet environment variable `OVERRIDE_CONFIG_URL`

**Comment by shawaj** [comment]
@vpetersson it is automatically generated and deployed....
https://github.com/NebraLtd/hm-block-tracker/blob/master/.github/workflows/run-update.yml

**Comment by vpetersson** [comment]
Ok, need to patch that for staging vs production then.

**Comment by vpetersson** [comment]
- [x] The `docker.config` file is now automatically generated as part of the GitHub Actions workflow for stage vs production
- [x] TestNet now points towards the staging environment
- [ ] Update the Cronjob to build both staging and production snapshots
