### ISSUE TITLE
Migrate from cronjob to systemd timer

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-block-tracker#46]
Right now we are running [create_snapshot.sh](https://github.com/NebraLtd/hm-block-tracker/blob/master/snapshotter/create_snapshot.sh) using a Cronjob. Instead, let's move this to a Systemd timer, such that we get more robust error handling as well as better logging.

While we are at it, let's also structure this a bit better such that we base this on the git repo.

## Checklist

- [x] Create a new runtime user (that is part of the `docker` group)
- [x] Check out this repository using the above user
- [x] Create a Systemd Timer that runs the Cronjob from the code repository above (such that we can do a simple `git pull` to bring in the latest changes)

**Comment by robputt** [comment]
User added called snapshot and added to docker group.
