### ISSUE TITLE
Stabilize snapshotter following light hotspot changes

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-block-tracker#96]
https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1652633776944869

Related to:
- https://github.com/NebraLtd/hm-block-tracker/issues/61

Acceptance criteria:
- Instructions for updating miner and snapshotter configs.
- Instructions for updating snapshotter GA

**Comment by marvinmarnold** [comment]
The snapshotter server is getting stuck at `miner snapshot take /var/data/saved-snaps/latest` and responds with `RPC to 'miner@127.0.0.1' failed: timeout`.  Other commands like `miner info summary` return successfully.

Is this a known issue @KevinWassermann94 ?

**Comment by KevinWassermann94** [comment]
@marvinmarnold I've seen that before, but usually the snapshot might still be processing even if it throws this error

**Comment by marvinmarnold** [comment]
> @marvinmarnold I've seen that before, but usually the snapshot might still be processing even if it throws this error

Thanks for the clue @KevinWassermann94. Can you keep an eye on the fleet? I pushed new snapshots based on outputs that timeout: https://github.com/NebraLtd/hm-block-tracker/pull/97

**Comment by KevinWassermann94** [comment]
@marvinmarnold I'll keep monitoring, but so far it's looking good

**Comment by marvinmarnold** [comment]
@vpetersson we are planning to start on-call duty for snapshotter. We know it is going away with light miners, but want to use it as practice for more general on-call. To do this, we'd like to create a new role for on-call that has the necessary permissions. Then grant that role to individuals while they are assigned on-call.

To start, Viktor can you create an on-call role and grant it [osAdminLogin](https://cloud.google.com/compute/docs/access/iam#compute.osAdminLogin)?

**Comment by vpetersson** [comment]
I've tasked @htsili with setting up access via Cloudflare Access. 

@htsili Can you provide an update on this?

**Comment by marvinmarnold** [comment]
@htsili ping

**Comment by htsili** [comment]
@marvinmarnold I have created the role with permissions similar to the one of the osAdminLogin. If we want to lock down this role into a specific resource we will have to set a condition each time we grant the role to a specific user. You can't set conditions into the role resource only when you assign it to a user. Let me know if that's ok for you. Otherwise, we can look into Cloudflare access.

**Comment by marvinmarnold** [comment]
Great. Can you assign it to @pritamghanghas to start? How do you recommend we rotate through the role normally? Does Cloudflare access offer any features we don't get doing it this way?

@NebraLtd/device-team I've started documenting a playbook for on-call here: https://docs.google.com/document/d/1EqXUbZjsCd4hK6YGQAnAOFIOOj_NHVCJFQbTj6Ru32E/edit?usp=sharing and taken care of updating the snapshotter for 2022.06.09.0.

**Comment by marvinmarnold** [comment]
@pritamghanghas you should have access to the snapshotter compute instance now. Can you try connecting and restarting the miner docker image to validate the connection is working?

**Comment by pritamghanghas** [comment]
@marvinmarnold can't access into it.
![image](https://user-images.githubusercontent.com/6928727/173415915-7ac42e14-d83f-4a59-b9e0-18c9138e636c.png)

**Comment by marvinmarnold** [comment]
@htsili ^^

**Comment by htsili** [comment]
> @htsili ^^

I spoke today with @pritamghanghas and I did some debugging on my own on this.
The IAM conditions don't work correctly for the compute instances.
We will have to go with the Cloudflare zero trust solution.
@vpetersson can you grant me access to Cloudflare so I can set this up?

**Comment by marvinmarnold** [comment]
@shawaj Harry needs Cloudflare access in order to setup on-call permissions. Can you please help?

**Comment by shawaj** [comment]
What's the email address @marvinmarnold ? And not sure what access is needed for it? Any ideas?

**Comment by htsili** [comment]
@shawaj 
My email address is harry.tsiligiannis@gmail.com.
If you have an enterprise plan in Cloudflare I would like the following roles.

- Cloudflare Access
- Cloudflare Zero Trust
- DNS

**Comment by htsili** [comment]
@shawaj 
No, I don't have a @nebra.com email.

**Comment by marvinmarnold** [comment]
@shawaj could you please provide Harry the permissions?

Cloudflare Access
Cloudflare Zero Trust
DNS
SSL/TLS, Caching, Performance, Page Rules, and Customization

**Comment by marvinmarnold** [comment]
@shawaj this is still blocked by Cloudflare permissions for Harry

**Comment by marvinmarnold** [comment]
@pritamghanghas can you go to `https://snapshotter.nebra.com/` and confirm that `sudo su` works? Can you then confirm that you can redeploy the snapshotter?

**Comment by pritamghanghas** [comment]
doesn't work
![image](https://user-images.githubusercontent.com/6928727/178429045-d19bef20-d113-40ec-94a4-ad8ba4fb6d34.png)

**Comment by htsili** [comment]
Hey @pritamghanghas please give it another try.

**Comment by pritamghanghas** [comment]
yes works now.

**Comment by htsili** [comment]
@marvinmarnold can we close this now?

**Comment by marvinmarnold** [comment]
Yea we can close this. Helium activated "light hotspots" today which means the snapshotter is deprecated now. We'll leave it running a few weeks until all hotspots have upgraded and we're confident Helium won't switch back.
